platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: pal-tracker

outputs:
  - name: build-output

run:
  path: echo
  args: [hello world]