platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
  - name: pal-tracker

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd pal-tracker
    chmod +x gradlew
    ./gradlew build
    cp build/libs/pal-tracker.jar ../build-output